### ISSUE TITLE
vertex ai出现 Error 500错误

### ISSUE THREAD

**Issue by kafuuchino-s** [yym68686/uni-api#101]
api.yaml内容如下
```
providers:
  - provider: vertex_1
    project_id: pacific-torus-456206-t3
    private_key: "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n"
    client_email: xxxxx@pacific-torus-456206-t3.iam.gserviceaccount.com
    model:
      - gemini-2.5-pro-exp-03-25: gemini-2.5-pro-exp
      - gemini-2.5-pro-preview-03-25: gemini-2.5-pro-preview
      - gemini-2.0-flash-001: gemini-2.0-flash
      - gemini-2.5-pro-preview-03-25: gemini-2.5-pro-preview-search
      - gemini-2.0-flash-001: gemini-2.0-flash-search
      - gemini-2.0-flash-lite-001: gemini-2.0-flash-lite
    tools: true
api_keys:
  - api: sk-xxx # API Key，用户使用本服务需要 API key，必填
    model: # 该 API Key 可以使用的模型，必填。默认开启渠道级轮询负载均衡，每次请求模型按照 model 配置的顺序依次请求。与 providers 里面原始的渠道顺序无关。因此你可以设置每个 API key 请求顺序不一样。
      - vertex_1/*
      - huoshan/*
      - poe/*
    role: openwebui # 设置 API key 的别名，选填。请求日志会显示该 API key 的别名。如果 role 为 admin，则仅有此 API key 可以请求 v1/stats,/v1/generate-api-key 端点。如果所有 API key 都没有设置 role 为 admin，则默认第一个 API key 为 admin 拥有请求 v1/stats,/v1/generate-api-key 端点的权限。
    preferences:
      SCHEDULING_ALGORITHM: random # 当 SCHEDULING_ALGORITHM 为 fixed_priority 时，使用固定优先级调度，永远执行第一个拥有请求的模型的渠道。默认开启，SCHEDULING_ALGORITHM 缺省值为 fixed_priority。SCHEDULING_ALGORITHM 可选值有：fixed_priority，round_robin，weighted_round_robin, lottery, random。
      # 当 SCHEDULING_ALGORITHM 为 random 时，使用随机轮训负载均衡，随机请求拥有请求的模型的渠道。
      # 当 SCHEDULING_ALGORITHM 为 round_robin 时，使用轮训负载均衡，按照顺序请求用户使用的模型的渠道。
      AUTO_RETRY: true # 是否自动重试，自动重试下一个提供商，true 为自动重试，false 为不自动重试，默认为 true。也可以设置为数字，表示重试次数。
      ENABLE_MODERATION: false # 是否开启消息道德审查，true 为开启，false 为不开启，默认为 false，当开启后，会对用户的消息进行道德审查，如果发现不当的消息，会返回错误信息。
preferences: # 全局配置
  model_timeout: # 模型超时时间，单位为秒，默认 100 秒，选填
    default: 30 # 模型没有设置超时时间，使用默认的超时时间 10 秒，当请求的不在 model_timeout 里面的模型时，超时时间默认是 10 秒，不设置 default，uni-api 会使用 环境变量 TIMEOUT 设置的默认超时时间，默认超时时间是 100 秒
    gemini-2.5-pro-preview: 100
    gemini-2.5-pro-exp: 100
  cooldown_period: 300 # 渠道冷却时间，单位为秒，默认 300 秒，选填。当模型请求失败时，会自动将该渠道排除冷却一段时间，不再请求该渠道，冷却时间结束后，会自动将该模型恢复，直到再次请求失败，会重新冷却。当 cooldown_period 设置为 0 时，不启用冷却机制。
  rate_limit: 999999/min # uni-api 全局速率限制，单位为次数/分钟，支持多个频率约束条件，例如：15/min,10/day。默认 999999/min，选填。
  keepalive_interval: # 心跳间隔，单位为秒，默认 80 秒，选填。适合当 uni-api 域名托管在 cloudflare 并使用推理模型时使用。
    gemini-2.5-pro-preview: 50 # 模型 gemini-2.5-pro 的心跳间隔为 50 秒，此数值必须小于 model_timeout 设置的超时时间，否则忽略此设置。
    gemini-2.5-pro-exp: 50
```
docker日志如下：
```
1282025-04-16 03:42:42,206 - uni-api - INFO - provider: vertex_Kozccm_1 model: gemini-2.5-pro-preview engine: vertex-gemini role: openwebui
1292025-04-16 03:42:42,206 - uni-api - ERROR - Error 500 with provider vertex_Kozccm_1 API key: None: local variable 'project_id' referenced before assignment
1302025-04-16 03:42:42,206 - uni-api - INFO - provider: vertex_Kozccm_1 model: gemini-2.5-pro-preview engine: vertex-gemini role: openwebui
1312025-04-16 03:42:42,206 - uni-api - ERROR - Error 500 with provider vertex_Kozccm_1 API key: None: local variable 'project_id' referenced before assignment
1322025-04-16 03:43:07,187 - uni-api - INFO - provider: huoshan model: deepseek-v3 engine: gpt role: translator
```
