### ISSUE TITLE
可以支持gemini新的url-context工具吗

### ISSUE THREAD

**Issue by oyasumiaiko** [yym68686/uni-api#122]
https://ai.google.dev/gemini-api/docs/url-context

希望能在启用search时候一同打开

**Comment by yym68686** [comment]
你好，已支持该特性。使用方法已经更新到文档。下面是一个示例配置：

```yaml
  - provider: gemini
    base_url: https://generativelanguage.googleapis.com/v1beta
    api: xxx
    model:
      - gemini-2.5-flash-preview-05-20: gemini-2.5-flash-search
    preferences:
      post_body_parameter_overrides:
        gemini-2.5-pro-search:
          tools:
            - google_search: {} # gemini-2.5-pro 不支持 url_context
        gemini-2.5-flash-search:
          tools:
            - google_search: {}
            - url_context: {}
```
