### ISSUE TITLE
No assistant content

### ISSUE THREAD

**Issue by DarremMolko** [yym68686/uni-api#125]
I noticed there's no assistant content with thinking budget higher than 0 for image descriptions. There's no error logs so I'm not really sure if this is a bug with uni-api or Google itself.

## API Request 1: Image Description with gemini-2.5-flash-think-24576

```bash
curl -X POST https://api.example.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-123456789" \
  -d '{
    "model": "gemini-2.5-flash-think-24576",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "Describe the content of this image."
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://img.example.com/photos/file_34.jpg"
            }
          }
        ]
      }
    ],
    "max_tokens": 100
  }'
```

**Response:**

```json
{
  "id": "chatcmpl-VyjPpU7OQ8ldx54UgM3Uh7No2DEbl",
  "object": "chat.completion",
  "created": 1747841220,
  "model": "gemini-2.5-flash-preview-05-20",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "",
        "refusal": null,
        "reasoning_content": "**Analyzing the Visual Narrative**\n\nOkay, so the user wants a description of the image. My job is to translate what I see into a detailed explanation. That means I need to break down the visuals, taking into account the subject, style, mood, and any elements that stand out.\n\nInitial impressions tell me we're looking at a young, female anime/manga-style character. The outdoor setting, specifically a garden, is also immediately apparent. These are the foundational elements to begin my interpretation.\n"
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 266,
    "completion_tokens": 0,
    "total_tokens": 266
  },
  "system_fingerprint": "fp_a7d06e42a7"
}
```

## API Request 2: Image Description with gemini-2.5-flash-think-0

```bash
curl -X POST https://api.example.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer sk-123456789" \
  -d '{
    "model": "gemini-2.5-flash-think-0",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "Describe the content of this image."
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://img.example.com/photos/file_34.jpg"
            }
          }
        ]
      }
    ],
    "max_tokens": 100
  }'
```

**Response:**

```json
{
  "id": "chatcmpl-KuSRkYL2vwgTKivDoxJFshnexhVbv",
  "object": "chat.completion",
  "created": 1747841268,
  "model": "gemini-2.5-flash-preview-05-20",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "This image is a digital illustration in an anime style, featuring a young female character in a lush, outdoor setting filled with greenery and flowers.\n\nHere's a breakdown of the content:\n\n*   **Character:** The central focus is a girl with short, brown hair and large, expressive eyes that are a warm brown color. She has a gentle smile on her face and light pink blush on her cheeks. She is wearing a large, teal-colored bow or headpiece decorated with floral patterns",
        "refusal": null
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 266,
    "completion_tokens": 100,
    "total_tokens": 366
  },
  "system_fingerprint": "fp_a7d06e42a7"
}
```

**Comment by yym68686** [comment]
Hello, I have already fixed this bug.

**Comment by DarremMolko** [comment]
I'm using the latest version (1.5.44) but I'm still getting no assistant content with gemini-2.5-flash-think-24576.

**Comment by yym68686** [comment]
This is because your max_tokens setting is too small.

<img width="1055" alt="Image" src="https://github.com/user-attachments/assets/5c0d7fec-a0f0-475c-ab12-2f2e82a5151b" />

**Comment by DarremMolko** [comment]
I tried with "max_tokens": 1000 and I still got no assistant content. Then I tried "max_tokens": null and it triggered this error in the logs:
```
2025-05-22 18:21:54,073 - uni-api - ERROR - Unknown role: None, parsed_data: [{'candidates': [{'finishReason': 'OTHER', 'index': 0}], 'usageMetadata': {'promptTokenCount': 266, 'totalTokenCount': 1417, 'promptTokensDetails': [{'modality': 'TEXT', 'tokenCount': 8}, {'modality': 'IMAGE', 'tokenCount': 258}], 'thoughtsTokenCount': 1151}, 'modelVersion': 'models/gemini-2.5-flash-preview-05-20'}]

```

**Comment by yym68686** [comment]
I guess the image violated the rules. This error means that Gemini blocked the response. I suggest using a different image.

**Comment by DarremMolko** [comment]
I tried with a more generic image (an screenshot of my desktop), with max_tokens 1000, but still the same. It still works fine with think-0 and I can live with that, so I can close this issue if you want.

Anyway this is my config in case it helps some way:

```yaml
providers:
  - provider: gemini
    base_url: https://generativelanguage.googleapis.com/v1beta
    api:
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
      - AIzaSyXXXXXXXXXXXXXXXXXX
    model:
      - gemini-2.5-pro-exp-03-25
      - gemini-2.5-pro-preview-05-06
      - gemini-2.5-pro-preview-05-06: gemini-2.5-pro-search
      - gemini-2.5-pro-preview-05-06: gemini-2.5-pro-think-24576-search
      - gemini-2.5-pro-preview-05-06: gemini-2.5-pro-think-24576
      - gemini-2.5-pro-preview-05-06: gemini-2.5-pro-think-0-search
      - gemini-2.5-pro-preview-05-06: gemini-2.5-pro-think-0
      - gemini-2.5-flash-preview-05-20
      - gemini-2.5-flash-preview-05-20: gemini-2.5-flash-search
      - gemini-2.5-flash-preview-05-20: gemini-2.5-flash-think-24576-search
      - gemini-2.5-flash-preview-05-20: gemini-2.5-flash-think-24576
      - gemini-2.5-flash-preview-05-20: gemini-2.5-flash-think-0-search
      - gemini-2.5-flash-preview-05-20: gemini-2.5-flash-think-0
      - text-embedding-004
      - gemini-embedding-exp
    tools: true
    preferences:
      post_body_parameter_overrides:
        gemini-2.5-pro-search:
          tools:
            - google_search: {}
        gemini-2.5-flash-search:
          tools:
            - google_search: {}
            - url_context: {}
        gemini-2.5-pro-think-0-search:
          tools:
            - google_search: {}
        gemini-2.5-flash-think-0-search:
          tools:
            - google_search: {}
            - url_context: {}
        gemini-2.5-pro-think-24576-search:
          tools:
            - google_search: {}
        gemini-2.5-flash-think-24576-search:
          tools:
            - google_search: {}
            - url_context: {}
    engine: gemini
```
