### ISSUE TITLE
建议加入provider频率限制功能

### ISSUE THREAD

**Issue by DullJZ** [yym68686/uni-api#15]
不同provider的速度不同，传统方法是给不同接口设置权重，开启自动超时轮询。

在已知TPM、RPM的情况下，希望通过不同接口的设置减少错误率。

例如，GitHub Models渠道每日限制50次、每分钟10次gpt-4o，那么达到该限制后就不再尝试这个渠道

**Comment by yym68686** [comment]
好的，我会考虑这个 featrue 的。开发完成后，我将在这里通知你❤️。

**Comment by 2328760190** [comment]
不知道佬能不能改的更详细一些:用一个参数设定该渠道所有key的并发限制
类似于上面说的，但更详细
举个例子🌰
cloudflare每个号的key是1w次/月，添加了10个key，在渠道位置设置所有key的用量限制是1w次/天，对于超限的key进行"冻结"，即不对其进行轮询，也可以尽可能减少类似429之类的错误，增加高并发时的速率，减少轮询反应所需时间☺

**Comment by yym68686** [comment]
> 不知道佬能不能改的更详细一些:用一个参数设定该渠道所有key的并发限制 类似于上面说的，但更详细 举个例子🌰 cloudflare每个号的key是1w次/月，添加了10个key，在渠道位置设置所有key的用量限制是1w次/天，对于超限的key进行"冻结"，即不对其进行轮询，也可以尽可能减少类似429之类的错误，增加高并发时的速率，减少轮询反应所需时间☺

好的，感谢更详细地描述需求。我开发的时候参考一下。

**Comment by 2328760190** [comment]
谢谢

**Comment by 2328760190** [comment]
冒昧的问一下大佬，您的开发进度如何

**Comment by yym68686** [comment]
近期更新了两个特性：

- 支持渠道冷却，当一个 API 渠道响应失败时，会自动将该渠道排除冷却一段时间，不再请求该渠道，冷却时间结束后，会自动将该模型恢复，直到再次请求失败，会重新冷却。
- 支持细粒度的模型超时时间设置，可以为每个模型设置不同的超时时间。

还没时间开发这个，还需要等一下。

**Comment by 2328760190** [comment]
好的，谢谢

**Comment by yym68686** [comment]
各位好，已增加频率限制功能，文档已更新，可以查看 README。下面我将详细介绍一下，新版本变化如下：

1. 增加了每个API key 的频率限制的支持，例如 flash 只能 15 rpm，可以设置（摘抄 README 原文）：

```
  - provider: gemini
    base_url: https://generativelanguage.googleapis.com/v1beta # base_url 支持 v1beta/v1, 仅供 Gemini 模型使用，必填
    api: # 支持多个 API Key，多个 key 自动开启轮训负载均衡，至少一个 key，必填
      - AIzaSyAN2k6IRdgw123
      - AIzaSyAN2k6IRdgw456
      - AIzaSyAN2k6IRdgw789
    model:
      - gemini-1.5-pro
      - gemini-1.5-flash-exp-0827: gemini-1.5-flash # 重命名后，原来的模型名字 gemini-1.5-flash-exp-0827 无法使用，如果要使用原来的名字，可以在 model 中添加原来的名字，只要加上下面一行就可以使用原来的名字了
      - gemini-1.5-flash-exp-0827 # 加上这一行，gemini-1.5-flash-exp-0827 和 gemini-1.5-flash 都可以被请求
    tools: true
    preferences:
      API_KEY_RATE_LIMIT: 15/min # 每个 API Key 每分钟最多请求次数，选填。默认为 999999/min
      API_KEY_COOLDOWN_PERIOD: 60 # 每个 API Key 遭遇 429 错误后的冷却时间，单位为秒，选填。默认为 60 秒
```

这样一旦有 API key 一分钟达到 15次，uni-api 将自动暂时屏蔽改 API key，直到几秒钟后检测到没有15次自动解锁。

2. 考虑到 API key 可能不止你一个人用，此时 uni-api 一分钟内计数 10次，但是你分享的人有人在这一分钟用了6次，其实此时 一分钟已经超过15次了。所以uni-api一旦收到 429 Too many requests 就自动雪藏 API_KEY_COOLDOWN_PERIOD 秒，不设置的话默认 60 秒。60秒后自动放出来溜一下，要是还是 429 继续雪藏。

3. 修复了其他 bug。

经过以上改进。在沉浸式翻译 10 次每秒的频率下，1 0个 Gemini API key 可以完美翻译不报错了。
