### ISSUE TITLE
并发好像有点低

### ISSUE THREAD

**Issue by Steven52065** [yym68686/uni-api#27]
使用docker部署，系统是Ubuntu 22.04.5 LTS
使用了相同的api后端，在沉浸翻译中直接使用api后端，并发能达到每秒十多次（一片一片的出来翻译结果）
但是经过uni-api后大概每秒只能输出一次翻译结果，日志中也是差不多每秒一次出现请求
服务器到本地测速上下行都有一两百，延迟稳定150ms左右，美西优化。
使用了长亭雷池 WAF 防火墙，但是关闭了对应uni-api接口的频率限制（关闭限制之前也没看到有访问频率过快的警告）
请求时cpu波动不大，内存快占满了（会是这个的影响吗？）
这是api,yaml的配置
```
providers:
  - provider: ai1 # 服务提供商名称, 如 openai、anthropic、gemini、openrouter、deepbricks，随便取名字，必填
    base_url: https://api....i/v1/chat/completions # 后端服务的API地址，必填
    api: sk-VmW... # 提供商的API Key，必填
    model:
      - gpt-4o
      - chatgpt-4o-latest
      - gpt-4o-mini

  - provider: ai2# 服务提供商名称, 如 openai、anthropic、gemini、openrouter、deepbricks，随便取名字，必填
    base_url: https://api....i/v1/chat/completions # 后端服务的API地址，必填
    api: sk-SO7GS... # 提供商的API Key，必填
    model:
      - gpt-4o
      - chatgpt-4o-latest
      - gpt-4o-mini

api_keys:
  - api: sk-DT0...
    model: 
      - gpt-4o
      - chatgpt-4o-latest
      - gpt-4o-mini
    preferences:
      RATE_LIMIT: 9999999/hour
  - api: sk-99cM....
    model: 
      - gpt-4o-mini
    preferences:
      RATE_LIMIT: 9999999/hour

preferences: # 全局配置
  model_timeout: # 模型超时时间，单位为秒，默认 100 秒，选填
    gpt-4o: 10 # 模型 gpt-4o 的超时时间为 10 秒,gpt-4o 是模型名称，当请求 gpt-4o-2024-08-06 等模型时，超时时间也是 10 秒
    claude-3-5-sonnet: 10 # 模型 claude-3-5-sonnet 的超时时间为 10 秒，当请求 claude-3-5-sonnet-20240620 等模型时，超时时间也是 10 秒
    default: 10 # 模型没有设置超时时间，使用默认的超时时间 10 秒，当请求的不在 model_timeout 里面的模型时，超时时间默认是 10 秒，不设置 default，uni-api 会使用 环境变量 TIMEOUT 设置的默认超时时间，默认超时时间是 100 秒
    o1-mini: 30 # 模型 o1-mini 的超时时间为 30 秒，当请求名字是 o1-mini 开头的模型时，超时时间是 30 秒
    o1-preview: 100 # 模型 o1-preview 的超时时间为 100 秒，当请求名字是 o1-preview 开头的模型时，超时时间是 100 秒
  cooldown_period: 600 # 渠道冷却时间，单位为秒，默认 300 秒，选填。当模型请求失败时，会自动将该渠道排除冷却一段时间，不再请求该渠道，冷却时间结束后，会自动将该模型恢复，直到再次请求失败，会重新冷却。当 cooldown_period 设置为 0 时，不启用冷却机制。
```
