### ISSUE TITLE
Enhancement - API load balancing

### ISSUE THREAD

**Issue by ratu-sh** [yym68686/uni-api#31]
can you please add option to turn on load balancing on API inside provider section?

i use one free provider that gives for free some amount of tokens. i creates several accounts and gets its API keys.

i want to use them randomly and evenly - not by sequence from first to last.

i suggest it can looks like

```yaml
  - provider: XXX
    base_url: https://api.xxx/v1/chat/completions
    api: 
      - sk-XXXX
      - sk-XXXX
      - sk-XXXX
      - sk-XXXX
      - sk-XXXX
      - sk-XXXX
      - sk-XXXX	  
      - sk-XXXX
    model:
      - XXX
      - ***
      - XXX
    tools: true
    LB: random #(or true)
```

now i can achive this goal only if i create several separate providers for each API key and use option `SCHEDULING_ALGORITHM: random` like that:

```yaml
  - provider: ***
    base_url: https://***
    api: ***
    model:
      - ***
      - ***
    tools: true

  - provider: ***
    base_url: https://***
    api: ***
    model:
      - ***
      - ***
    tools: true

...

    preferences:
      SCHEDULING_ALGORITHM: random

```
