### ISSUE TITLE
关于对 Github Models 这类不包含 V1 的请求路径的处理

### ISSUE THREAD

**Issue by Atomesh** [yym68686/uni-api#33]
```py
class BaseAPI:
    def __init__(
        self,
        api_url: str = "https://api.openai.com/v1/chat/completions",
    ):
        if api_url == "":
            api_url = "https://api.openai.com/v1/chat/completions"
        self.source_api_url: str = api_url
        from urllib.parse import urlparse, urlunparse
        parsed_url = urlparse(self.source_api_url)
        if parsed_url.scheme == "":
            raise Exception("Error: API_URL is not set")
        if parsed_url.path != '/':
            before_v1 = parsed_url.path.split("/v1")[0]
        else:
            before_v1 = ""
        self.base_url: str = urlunparse(parsed_url[:2] + (before_v1,) + ("",) * 3)
        self.v1_url: str = urlunparse(parsed_url[:2]+ (before_v1 + "/v1",) + ("",) * 3)
        self.v1_models: str = urlunparse(parsed_url[:2] + (before_v1 + "/v1/models",) + ("",) * 3)
        if parsed_url.netloc == "api.deepseek.com":
            self.chat_url: str = urlunparse(parsed_url[:2] + ("/chat/completions",) + ("",) * 3)
        else:
            self.chat_url: str = urlunparse(parsed_url[:2] + (before_v1 + "/v1/chat/completions",) + ("",) * 3)
        self.image_url: str = urlunparse(parsed_url[:2] + (before_v1 + "/v1/images/generations",) + ("",) * 3)
        self.audio_transcriptions: str = urlunparse(parsed_url[:2] + (before_v1 + "/v1/audio/transcriptions",) + ("",) * 3)
        self.moderations: str = urlunparse(parsed_url[:2] + (before_v1 + "/v1/moderations",) + ("",) * 3)
        self.embeddings: str = urlunparse(parsed_url[:2] + (before_v1 + "/v1/embeddings",) + ("",) * 3)
```
在 BaseAPI 的处理中，对于 embeddings 等内容的处理会添加 v1
但在 github models 的请求中，base_url 分别为

- https://models.inference.ai.azure.com/chat/completions
- https://models.inference.ai.azure.com/embeddings

除了 Github Models 外应该还有不少的没有 v1 的 provider，此处是否应该做一个选项，而非像 deepseek 这样子一个个添加

```yaml
  - provider: GLM
    base_url: https://open.bigmodel.cn/api/paas/v4/chat/completions
    spilter: v4
    api: xxx
    model:
      - glm-4-flash
    tools: true
    notes: ''
  - provider: Github
    base_url: https://models.inference.ai.azure.com/chat/completions
    spilter: null
    api: xxx
    model:
      - glm-4-flash
    tools: true
    notes: ''
```

由于 BaseAPI 的入口很单一，所以选择增加一个 spliter 选项，改变其行为在修改上应该也不会过于麻烦

- 对 GLM 使用 v4 代替原本代码中 v1 的部分
- 对 Github 无分隔符的，则直接使用其 domain 作为 base_url

又或者强制使用输入的 base_url 加上对应 endpoint，不再对 v1 进行分割
```yaml
  - provider: GLM
    base_url: https://open.bigmodel.cn/api/paas/v4/
    focus_base: true
    api: xxx
    model:
      - glm-4-flash
    tools: true
    notes: ''
  - provider: Github
    base_url: https://models.inference.ai.azure.com/
    focus_base: true
    api: xxx
    model:
      - glm-4-flash
    tools: true
    notes: ''
```

- 对 GLM https://open.bigmodel.cn/api/paas/v4/ 后会直接添加 embeddings 作为端点
- 对 Github 则也是直接 https://models.inference.ai.azure.com/ 后会直接添加 embeddings 作为端点

即不再进行 v1 的防呆判断

理论上需要在
![image](https://github.com/user-attachments/assets/0fe06548-7cdb-4be9-8f7f-ff509be4d158)
这几个地方进行修改即可，我个人认为第二种修改方式应该合适些，因为对于自定义的情况而言，那样可以最大限度的减少程序对输入配置的影响，如果您觉得这样修改合适，时间也不是很充裕，我也可以进行对应的修改，提个 PR

非常感谢
