### ISSUE TITLE
 gpt-o1 model Bug in `aimlapi.com` provider

### ISSUE THREAD

**Issue by ratu-sh** [yym68686/uni-api#37]
When using https://aimlapi.com/ gpt-o1 model - telegram bot send full json from query instead of only text answer from field `content`

```
ME, [08.11.2024 13:54]
кто ты и что умеешь?

AI, [08.11.2024 13:54]
201 Created {"error":"All gpt-o1 error: {'id': 'chatcmpl-ARGvfaHKSnRngtgpeaosWE5IXNZ7L', 'object': 'chat.completion', 'choices': [{'index': 0, 'finish_reason': 'stop', 'message': {'role': 'assistant', 'content': 'Я — искусственный интеллект, разработанный компанией OpenAI. Я могу отвечать на вопросы, предоставлять информацию по различным "}
```

```
INFO:     10.60.0.2:37738 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-11-08 10:54:39,029 - uni-api - INFO - provider: aimlapi-chatgpt model: gpt-o1                 engine: o1
2024-11-08 10:54:59,764 - uni-api - ERROR - Error 201 with provider aimlapi-chatgpt API key: **************: {'id': 'chatcmpl-ARGvfaHKSnRngtgpeaosWE5IXNZ7L', 'object': 'chat.completion', 'choices': [{'index': 0, 'finish_reason': 'stop', 'message': {'role': 'assistant', 'content': 'Я — искусственный интеллект, разработанный компанией OpenAI. Я могу отвечать на вопросы, предоставлять информацию по различным 
timeout_value 30
```

**Comment by ratu-sh** [comment]
also when using gpt-o1-mini - nothing appears in logs and bot answers like that

```
ME, [08.11.2024 13:59]
Кто ты?

AI, [08.11.2024 13:59]
'tools'
```

**Comment by yym68686** [comment]
Please provide me with a temporary API key from the API provider, otherwise I won't be able to reproduce your bug. Please send the API key, API URL, and model name to the email: yym68686@outlook.com.

**Comment by ratu-sh** [comment]
> Please provide me with a temporary API key from the API provider, otherwise I won't be able to reproduce your bug. Please send the API key, API URL, and model name to the email: [yym68686@outlook.com](mailto:yym68686@outlook.com).

send you API key right now.

this API key is paid and valid up to Nov 14, 2024
remaining tokens  9,049,931

**Comment by ratu-sh** [comment]
i don't know if my config is valid but i used this one

```
  - provider: aimlapi-chatgpt
    base_url: https://api.aimlapi.com/chat/completions
    api: ******************
    model:
      - o1-preview: gpt-o1
      - o1-preview-2024-09-12: gpt-o1
      - o1-mini: gpt-o1-mini
      - o1-mini-2024-09-12: gpt-o1-mini
      - gpt-4o: gpt-4o
      - gpt-4o-2024-08-06: gpt-4o
      - gpt-4o-2024-05-13: gpt-4o
      - gpt-4o-mini: gpt-4o-mini
      - gpt-4o-mini-2024-07-18: gpt-4o-mini
      - chatgpt-4o-latest: gpt-4o
      - gpt-4-turbo: gpt-4-turbo
      - gpt-4-turbo-2024-04-09: gpt-4-turbo
      - gpt-4: gpt-4
      - gpt-4-0125-preview: gpt-4
      - gpt-4-1106-preview: gpt-4
      - gpt-3.5-turbo: gpt-3.5-turbo
      - gpt-3.5-turbo-0125: gpt-3.5-turbo
      - gpt-3.5-turbo-1106: gpt-3.5-turbo
      - gpt-3.5-turbo-instruct: gpt-3.5-turbo
    tools: true
    preferences:
      api_key_rate_limit:
        default: 1500/hour
      api_key_cooldown_period: 60
      model_timeout:
        gpt-o1-mini: 30
        gpt-o1: 100
        default: 30
```

the API docs here - https://docs.aimlapi.com/glossary/concepts#base-url

here is button "Test it" to get all models list - https://docs.aimlapi.com/api-overview/model-database
