### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by shuimu5418** [yym68686/uni-api#42]
环境：vercel
部分配置：
```
  - provider: oai1
    base_url: https://api.openai.com/v1/chat/completions
    api: sk-11111
    model:
      - gpt-4o-latest : gpt-4o

  - provider: different_oai2
    base_url: https://api.closeai.com/v1/chat/completions
    api: sk-22222
    model:
      - gpt-4o

api_keys:
  - api: sk-12345
    model:
      - oai1/*
      - different_oai2/*
    role: admin
```
操作：
1. 某个后端报错，不可使用或抽风且正好被碰上。
2. 再次请求，返回500，vercel日志记录event loop is closed。
3. 继续请求，每请求两次，正常一次，500一次。
