### ISSUE TITLE
请求对 gemini embeddings 的支持

### ISSUE THREAD

**Issue by LjhAUMEM** [yym68686/uni-api#44]
使用的配置文件，目前无法使用text-embedding-004和embedding-001模型
[相关官方文档 https://ai.google.dev/api/embeddings](https://ai.google.dev/api/embeddings)
```yaml
providers:
  - provider: gemini
    base_url: https://generativelanguage.googleapis.com/v1beta
    api:
      - xxx
    model:
      - gemini-1.5-flash: gpt-4o-mini
      - gemini-1.5-flash
      - text-embedding-004
      - embedding-001
    tools: true
    preferences:
      api_key_rate_limit:
        gpt-4o-mini: 15/min
        gemini-1.5-flash: 15/min
        text-embedding-004: 1500/min
        embedding-001: 1500/min
      api_key_cooldown_period: 60
      api_key_schedule_algorithm: round_robin
      proxy: socks5://host.docker.internal:10808
api_keys:
  - api: xxx
    model:
      - all
```

**Comment by LjhAUMEM** [comment]
看了一下代码，目前gemini engine仅支持chat，单独再开一个gemini-embed engine可能更容易一点
```yaml
providers:
  - provider: gemini chat
    engine: gemini
    base_url: https://generativelanguage.googleapis.com/v1beta
    api:
      - xxx
    model:
      - gemini-1.5-flash: gpt-4o-mini
      - gemini-1.5-flash
    tools: true
    preferences:
      api_key_rate_limit:
        gpt-4o-mini: 15/min
        gemini-1.5-flash: 15/min
      api_key_cooldown_period: 60
      api_key_schedule_algorithm: round_robin
      proxy: socks5://host.docker.internal:10808
  - provider: gemini embeddings
    engine: gemini-embed
    base_url: https://generativelanguage.googleapis.com/v1beta
    api:
      - xxx
    model:
      - text-embedding-004
      - embedding-001
    preferences:
      api_key_rate_limit:
        text-embedding-004: 1500/min
        embedding-001: 1500/min
      api_key_cooldown_period: 60
      api_key_schedule_algorithm: round_robin
      proxy: socks5://host.docker.internal:10808
api_keys:
  - api: xxx
    model:
      - all
```
