### ISSUE TITLE
bug: gemini 的 base_url 不支持反代的地址

### ISSUE THREAD

**Issue by LjhAUMEM** [yym68686/uni-api#45]
我注意到 gemini engine 的 base_url 目前只是作为判断 api 版本来使用，希望 base_url 支持反代的地址，这样无需使用正向代理也可以使用

https://github.com/yym68686/uni-api/blob/88cac46b648d4f1abe093409bc404be6c9913c62/request.py#L126-L130

比如

```yaml
providers:
  - provider: gemini
    engine: gemini
    base_url: http://host.docker.internal:8888 # 我在本机 8888 反代了 https://generativelanguage.googleapis.com 或者其他任何反代 https://generativelanguage.googleapis.com 的地址
    gemini_version: v1beta # api 版本新建一个配置项来设置
    api:
      - xxx
    model:
      - gemini-1.5-flash: gpt-4o-mini
      - gemini-1.5-flash
    tools: true
    preferences:
      api_key_rate_limit:
        gpt-4o-mini: 15/min
        gemini-1.5-flash: 15/min
      api_key_cooldown_period: 60
      api_key_schedule_algorithm: round_robin
api_keys:
  - api: xxx
    model:
      - all
```
