### ISSUE TITLE
测试发现 gemini v1 版本不支持 systemInstruction 字段

### ISSUE THREAD

**Issue by LjhAUMEM** [yym68686/uni-api#47]
测试发现 gemini v1 版本不支持 systemInstruction 字段，但是 safetySettings 字段是支持的

测试请求

```shell
curl -X POST \
  'https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash-002:generateContent?key=$GOOGLE_API_KEY' \
  -H 'Content-Type: application/json' \
  -d '{
    "contents": [{"role": "user", "parts": [{"text": "Hello!"}]}],
    "safetySettings": [
      {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
      {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
      {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
      {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"}
    ],
    "systemInstruction": {"parts": [{"text": "You are a helpful assistant."}]}
  }' --proxy http://127.0.0.1:10809
```

响应

```json
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"systemInstruction\": Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"systemInstruction\": Cannot find field."
          }
        ]
      }
    ]
  }
}
```

删除 systemInstruction 后

```shell
curl -X POST \
  'https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash-002:generateContent?key=$GOOGLE_API_KEY' \
  -H 'Content-Type: application/json' \
  -d '{
    "contents": [{"role": "user", "parts": [{"text": "Hello!"}]}],
    "safetySettings": [
      {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
      {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
      {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
      {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"}
    ]
  }' --proxy http://127.0.0.1:10809
```

响应

```json
{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "Hello there! How can I help you today?\n"
          }
        ],
        "role": "model"
      },
      "finishReason": "STOP",
      "safetyRatings": [
        {
          "category": "HARM_CATEGORY_HATE_SPEECH",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HARASSMENT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          "probability": "NEGLIGIBLE"
        }
      ],
      "avgLogprobs": -0.0009812796488404274
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 3,
    "candidatesTokenCount": 11,
    "totalTokenCount": 14
  },
  "modelVersion": "gemini-1.5-flash-002"
}
```

**Comment by yym68686** [comment]
uni-api 仅支持 OpenAI 格式的请求，其他格式不支持。

**Comment by LjhAUMEM** [comment]
配置文件里如果设置 gemini 版本为 v1 则会一直报错，原因应该就是上面提到的

```yaml
providers:
  - provider: gemini
    base_url: https://generativelanguage.googleapis.com/v1
    api:
      - xxx
    model:
      - gemini-1.5-flash-001: gpt-4o-mini
      - gemini-1.5-flash-001
    tools: true
    preferences:
      api_key_rate_limit:
        gpt-4o-mini: 15/min
        gemini-1.5-flash-001: 15/min
      api_key_cooldown_period: 60
      api_key_schedule_algorithm: round_robin
      proxy: socks5://host.docker.internal:10808
api_keys:
  - api: xxx
    model:
      - all
```
