### ISSUE TITLE
有对豆包模型的支持吗

### ISSUE THREAD

**Issue by SenLief** [yym68686/uni-api#49]
我看配置文件中貌似没有对豆包模型的支持，后续有计划的吗？

**Comment by yym68686** [comment]
如果豆包支持 OpenAI 格式就是支持的。如果你尝试后不能使用，可以邮件发一个临时的 key 帮你适配一下。

**Comment by SenLief** [comment]
经测试可以使用
```
- provider: doubao
    base_url: https://ark.cn-beijing.volces.com/api/v3/chat/completions
    api: # 支持多个 API Key，多个 key 自动开启轮训负载均衡，至少一个 key，必填
      - xxxxxxxxxxxxxxxxxxx
    model:
      - ep-202411xxxxxxx Doubao-lite-32k
      - ep-202410xxxxxxx: Doubao-pro-32k
``` 
不过这些模型貌似都不支持openai类似的函数调用，我使用全部都不行，不知道是不是参数有问题，有测试硅基流动和豆包都不行。
