### ISSUE TITLE
硅基流动视觉模型失效

### ISSUE THREAD

**Issue by Masque423** [yym68686/uni-api#52]
### 使用的是 Cherry Studio 客户端，这是直接调用硅基官方api的 Qwen2-VL-72B，视觉模型正常:
![image](https://github.com/user-attachments/assets/6337a532-0cbe-41bc-a643-8d5b60caaf1e)

### 这是 api.yaml 配置：
```yaml
  - provider: Siliconflow
    base_url: https://api.siliconflow.cn/v1/chat/completions
    api:
    model:
      - 'Qwen/Qwen2-VL-72B-Instruct': Qwen2-VL-72B-Instruct-sf
```

### 这是使用 uni-api ，视觉模型不正常：
![image](https://github.com/user-attachments/assets/132e3f07-9b11-4659-81b8-ea219c49c690)
