### ISSUE TITLE
Cohere 支持

### ISSUE THREAD

**Issue by nobodysclown** [yym68686/uni-api#6]
https://api.cohere.com/v1/chat

报错

`
{
  "message": "All command-r-plus error: {'message': 'invalid request: message must be at least 1 token long or tool results must be specified.'}"
}
`

**Comment by yym68686** [comment]
目前还没有支持 Cohere，后面我支持一下，在这里提醒你一下。

**Comment by yym68686** [comment]
现在已经支持 Cohere 系列模型。

**Comment by nobodysclown** [comment]
感谢，已经用上了，我试了一下 Groq 也是支持的，可以在文档里说明一下

```
  - provider: groq
    base_url: https://api.groq.com/openai/v1/chat/completions
    api: gsk_xxxx
    model:
      - llama-3.1-70b-versatile
```
