### ISSUE TITLE
'ImageGenerationRequest' object has no attribute 'messages'

### ISSUE THREAD

**Issue by DarremMolko** [yym68686/uni-api#60]
Is this a bug or am I doing something wrong?

![IMG_20250116_071701_514](https://github.com/user-attachments/assets/834afebe-ee84-41b4-b1fc-393d1a9bfc45)

```
## config.yaml

- provider: siliconflow
    base_url: https://api.siliconflow.cn/v1/chat/completions
    api:
      - sk-XXXXXXXXXXXXXXXXXXXXX
    model:
      - stabilityai/stable-diffusion-3-5-large: stable-diffusion-3-5-large
      - Qwen/QVQ-72B-Preview: qvq-72b-preview
      - deepseek-ai/DeepSeek-V2.5: deepseek-v2.5
      - Qwen/Qwen2-VL-72B-Instruct: qwen2-vl-72b-instruct
      - AIDC-AI/Marco-o1: marco-o1
    tools: true
    engine: gpt

```
