### ISSUE TITLE
please add support of `1minai` API

### ISSUE THREAD

**Issue by chelaxian** [yym68686/uni-api#62]
please add support of `1minai` API

API reference: https://gleaming-wren-2af.notion.site/1min-AI-API-Docs-111af080bd8f8046a4e6e1053c95e047
Model list: https://gleaming-wren-2af.notion.site/1min-AI-API-Docs-111af080bd8f8046a4e6e1053c95e047#11baf080bd8f80c2bf2dc04a5fd3f77f

now it not work with config like

```yaml
  - provider: 1minai
    base_url: https://api.1min.ai/api/features?isStreaming=true
    api: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    model:
      - "o1-preview": GPTo1_PREVIEW
      - "o1-mini": GPTo1_MINI
      - "gpt-4o-mini": GPT4o_MINI
      - "gpt-4o": GPT4o
      - "gpt-4-turbo": GPT4_TURBO
      - "gpt-4": GPT4
      - "gpt-3.5-turbo": GPT35
      - "dall-e-2": DALLE2
      - "dall-e-3": DALLE3
      - "claude-instant-1.2": CLAUDE_INSTANT
      - "claude-2.1": CLAUDE2
      - "claude-3-5-sonnet-20240620": CLAUDE3_5_SONNET
      - "claude-3-opus-20240229": CLAUDE3_OPUS
      - "claude-3-sonnet-20240229": CLAUDE3_SONNET
      - "claude-3-haiku-20240307": CLAUDE3_HAIKU
      - "gemini-1.0-pro": GEMINI
      - "gemini-1.5-pro": GEMINI_1_5
      - "gemini-1.5-flash": GEMINI_1_5_FLASH
      - "mistral-large-latest": MISTRAL_LARGE_2
      - "mistral-small-latest": MISTRAL_SMALL
      - "mistral-nemo": MISTRAL_NEMO
      - "pixtral-12b": PIXTRAL_12B
      - "open-mixtral-8x22b": MIXTRAL_8x22B
      - "open-mixtral-8x7b": MIXTRAL_8x7B
      - "open-mistral-7b": MISTRAL_7B
      - "meta/llama-2-70b-chat": LLAMA
      - "meta/meta-llama-3-70b-instruct": LLAMA_3_70B_INSTRUCT
      - "meta/meta-llama-3.1-405b-instruct": LLAMA_3_1_405B_INSTRUCT
      - "black-forest-labs/flux-schnell": FLUX_SCHNELL
      - "black-forest-labs/flux-dev": FLUX_DEV
      - "black-forest-labs/flux-pro": FLUX_PRO
      - "black-forest-labs/flux-1.1-pro": FLUX_PRO_1_1
      - "mistralai/mixtral-8x7b-instruct-v0.1": MISTRAL
    tools: true
    #engine: openrouter
    preferences:
      api_key_rate_limit:
        default: 20/min,200/day
      api_key_cooldown_period: 60
```

in docker i see error logs:

```bash
2025-01-26 12:19:55,292 - uni-api - INFO - provider: 1minai      model: CLAUDE3_SONNET         engine: gpt role: admin

2025-01-26 12:19:55,688 - uni-api - ERROR - Error 401 with provider 1minai API key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: {'message': 'Missing API Key'}

INFO:     10.60.0.2:49022 - "POST /v1/chat/completions HTTP/1.1" 401 Unauthorized
```
