### ISSUE TITLE
gemini似乎无法自动获取模型？

### ISSUE THREAD

**Issue by railzy** [yym68686/uni-api#66]
providers部分配置

```yaml
providers:
  - provider: gemini # 服务提供商名称, 如 openai、anthropic、gemini、openrouter，随便取名字，必填
    base_url: https://generativelanguage.googleapis.com/v1beta # 后端服务的API地址，必填
    api: 
      # 提供商的API Key，必填，自动使用 base_url 和 api 通过 /v1/models 端点获取可用的所有模型。
      - AI……
    #model:
     # - gemini-2.0-flash-thinking-exp-01-21
```
部署在vercel上，只有在配置文件里手动输入，才能显示模型。
