### ISSUE TITLE
请支持渠道设置 request  自定义增加 headers。谢谢。

### ISSUE THREAD

**Issue by xjdata** [yym68686/uni-api#73]
如题。

```yaml
  - provider: gemini
    base_url: https://gemini.foo.bar/v1beta
    api: 
      - xxxxxxx 
    headers:
      - X-1: 具体的值
      - X-2: 另一个值
```

实际请求时， request 多增加 headers 配置的内容。
