### ISSUE TITLE
你好，请问下支持指定渠道随机请求吗？

### ISSUE THREAD

**Issue by zzy-life** [yym68686/uni-api#87]
项目非常好用！但是有个问题不知道怎么配置，比如我有渠道1,2,3
我想特定模型在渠道1，2上随机请求
全部请求失败了再请求渠道3

**Comment by zzy-life** [comment]
请问一下，这样可以吗？
```xml
api_keys:
  - api: sk-your-api-key
    model:
      - channel1/your-model-name: 5 # 权重为5
      - channel2/your-model-name: 5 # 权重为5
      - channel3/your-model-name # 没有权重，作为备用
    preferences:
      SCHEDULING_ALGORITHM: weighted_round_robin
      AUTO_RETRY: 2
```

**Comment by zzy-life** [comment]
核心意思就是渠道1和渠道2是低价中转，我想随机打到他们那，他们全失败了之后才请求官方

**Comment by yym68686** [comment]
README确实没有提供这方面的指导。这样设置即可：

```yaml
api_keys:
  - api: sk-xxx1
    model:
      - sk-xxx2/* # 渠道 1 2 采用随机轮训，失败后请求渠道3
      - aws/* # 渠道3 
    preferences:
      SCHEDULING_ALGORITHM: fixed_priority

  - api: sk-xxx2
    model:
      - anthropic/claude-3-7-sonnet # 渠道1
      - openrouter/claude-3-7-sonnet # 渠道2
    preferences:
      SCHEDULING_ALGORITHM: random # 渠道 1 2 采用随机轮训
```
