### ISSUE TITLE
Feature Request: 添加 SSE Keep-Alive 选项以防止流式传输超时（例如 Cloudflare 524）

### ISSUE THREAD

**Issue by hang333** [yym68686/uni-api#93]
## 背景

- **现状描述:**
    当 uni-api 部署在像 Cloudflare 这样的反向代理后面时，如果使用流式传输 (`stream=True`) 调用后端 AI 模型，并且该模型在返回第一个数据块之前需要较长的处理时间（例如，进行复杂的推理或“思考”），Cloudflare 可能会因为长时间没有数据通过连接而主动断开连接，导致客户端收到 HTTP 524 超时错误。
    目前，uni-api 的流式处理逻辑似乎是等待从实际的后端服务（如 OpenAI, Gemini, Claude 等）接收到第一个 SSE 事件或数据块后，才开始向客户端发送 SSE 事件。在这个等待期间，uni-api 与客户端之间的连接可能因为不活动而被中间的代理（如 Cloudflare）中断。

## 思路

为了解决这个问题，并提高 uni-api 在类似 Cloudflare 部署环境下的流式传输稳定性，建议添加一个可选的 SSE Keep-Alive 机制。

**核心想法:**

在 uni-api 等待后端模型返回第一个数据块的期间，定期向客户端发送一个“心跳”信号（SSE Keep-Alive 事件）。这个信号本身不包含实际的 AI 模型响应内容，其主要目的是保持客户端与 uni-api 之间的 TCP 连接活跃，防止被中间代理因超时而关闭。

**实现建议:**

1.  **引入配置项:** 在 `api.yaml` 的全局 `preferences` 部分（或者更细粒度的，如 `providers` 或 `api_keys` 的 `preferences` 中）添加配置项来控制此行为。例如：
    ```yaml
    preferences:
      # ... 其他全局配置 ...
      sse_keepalive:
        enabled: true  # 是否启用 SSE Keep-Alive, 默认为 false
        interval: 15   # 发送 Keep-Alive 信号的间隔（秒），例如 15 秒
    ```
2.  **Keep-Alive 信号格式:** 推荐使用 SSE 注释格式，例如发送 `": keepalive\n\n"`。这种格式通常会被客户端的 `EventSource` 实现忽略，不会触发 `onmessage` 事件，但能有效维持连接。
3.  **实现逻辑:**
    *   当收到一个 `stream=True` 的请求时，如果 `sse_keepalive.enabled` 为 `true`：
    *   启动一个并行的 `asyncio` 任务（或类似机制）。
    *   该任务以 `sse_keepalive.interval` 定义的间隔，向客户端发送 Keep-Alive 信号。
    *   一旦从后端服务接收到第一个有效的数据块，或者请求处理完成/出错，这个并行的 Keep-Alive 任务就应该停止。
    *   之后，uni-api 正常处理和转发来自后端服务的 SSE 事件流。

**好处:**

*   显著降低因后端处理延迟导致的 Cloudflare 524 或其他代理超时错误。
